### ISSUE TITLE
CPU usage maxed out

### ISSUE THREAD

**Issue by Z0l** [souliss/bindingopenhab2#1] opened 2018-10-07 20:01 UTC
Using this one instead of version 1 maxes out one CPU continuously :/ this is what threads gives:

openhab> threads 228
Thread 228 Thread-80 RUNNABLE
Stacktrace:
org.openhab.binding.souliss.handler.SoulissGatewayThread.run line: 80

System is Debian 9 with zulu JDK, 6GB RAM. If needed I can provide more debug info - let me know.

**Comment by kstubb** [comment] 2018-11-14 22:22
Hi Z0I;

A little help, if you don't mind.

How do I manually swap this binding out for the V1 binding? 

I'm on a Debian 9 system as well.  The only reference I find to org.openhab.binding.souliss is in /var/lib/tmp/mvn/org/openhab/binding (which I assume is where openhab stores downloaded bindings, if you don't have the addons package installed).

Do I simply replace the org.openhab.binding.souliss directory with this new binding?

Thanks!

**Comment by Z0l** [comment] 2018-11-15 14:51
You download the jar and copy it to /usr/share/openhab2/addons, then it will be available in Paper UI. Disable v1 before continuing. Since this supports autodiscovery, you only need to add your gateway as a thing and the rest will be auto-discovered.
Truth be told I jumped back on v1, because I had some other issues as well (rollershutter images were not showing the correct status).

**Comment by kstubb** [comment] 2018-11-15 15:46
Thanks.  I actually got it late last night, but didn't yet revisit this thread.

I tried to drop the .zip into addons, but that didn't work.  The short of it is, you need to download the .jar from the "Releases" section --> https://github.com/souliss/bindingopenhab2/releases and drop it into /usr/share/openhab2/addons/.

I do appreciate the answer though.

As for V1... the reason for me switching to V2 is that I was unable to get any output to control items in V1.  Originally, I was trying to get the Souliss Digital Thermostat to work.  I could read everything, including temperature, temperature as measured, humidity, setpoint, etc., but I couldn't get the power, fan, heating mode or the setpoint to actually SET values.  I'd pull the setpoint value as 23, set it to 21 and it would revert back to 23 without anything happening at the thermostat. So I tried a T14 with my garage door openers and couldn't get them to respond either.  Everything worked from the SoulissApp.

V2 seems to work fine with both T31 and T14 (plus T52, T53, T54) from what I have currently setup.  However, I do notice the CPU max out you describe in your OP.  Not sure what I can do to help trace / solve the problem, but let me know if I can. 
(Debian 9, 4GB
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode))

Just FYI - Thing auto-discovery worked well and actually detected my gateway.  I did add it through the PaperUI and auto-discovery did grab a couple typicals, but most of them I had to add manually.  I went back and removed the Gateway from PaperUI and added it manually in /things/, along with all the typicals I'm using for each node. Everything I have used thus far appears to be working correctly.

**Comment by lucacalcaterra** [comment] 2018-11-16 09:41
I had the same problem, I'm testing the latest release (of 6/11/18)  on openhab 2.4 snapshot (windows) and seems I have no problems. I do other tests and update you.
I must try on raspberry

**Comment by lucacalcaterra** [comment] 2018-11-16 12:12
No way... installed on raspberry 3 b+ openhab 2.3 . CPU 100% after discovered souliss gateway

**Comment by lucacalcaterra** [comment] 2018-12-21 15:56
Now the issue is resolved with latest release. Thanks to Tonino !

**Comment by FulvioSpelta** [comment] 2019-04-08 05:57
we can close the issue ?
Ciao

**Comment by kstubb** [comment] 2019-04-08 13:33
The issue has been resolved for me.  CPU usage averages 10-15%.

**Comment by Z0l** [comment] 2019-04-08 18:03
Same here. Can we make this the default binding in Openhab2?

**Comment by lucacalcaterra** [comment] 2019-04-08 18:18
The problem was a The threads of binding. @toninofazio worked  on it. For me Now it's ok, don't know if this the correct Branch of fixed version.

**Closed as completed** 2019-04-15 05:45 UTC
